services:
  diffusion_api:
    build:
      context: ./monkey_diffusion_api
      dockerfile: docker/Dockerfile
    container_name: diffusion_api
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./shared:/shared
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.diffusion_api.rule=PathPrefix(`/`)"
      - "traefik.http.services.diffusion_api.loadbalancer.server.port=3000"

  icecast:
    image: "rolla/icecast-kh"
    container_name: icecast2
    restart: always
    volumes:
      - ./icecast/icecast.xml:/home/icecast/config/icecast.xml
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.icecast.rule=PathPrefix(`/v1/diffusion/ice`)"
      - "traefik.http.services.icecast.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.ice-replace.replacepathregex.regex=^/v1/diffusion/ice/(.*)"
      - "traefik.http.middlewares.ice-replace.replacepathregex.replacement=/stream/$$1"
      - "traefik.http.routers.icecast.middlewares=ice-replace"

  # proxy:
  #   image: "nginx"
  #   container_name: proxy
  #   restart: always
  #   ports:
  #     - "$NGINX_PORT:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   networks:
  #     - default

  reverse-proxy:
    image: traefik:v3.1
    ports:
      - "$HTTP_PORT:80"
      - "$HTTPS_PORT:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yaml:/traefik.yaml
    labels:
      - "traefik.enable=false"

networks:
  default:
    name: monkeyradio_diffusion_network
    external: true
