services:
  diffusion_api:
    build:
      context: ./monkey_diffusion_api
      dockerfile: docker/Dockerfile
    container_name: diffusion_api
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./shared:/shared
    networks:
      - default

  icecast:
    image: "rolla/icecast-kh"
    container_name: icecast2
    restart: always
    volumes:
      - ./icecast/icecast.xml:/home/icecast/config/icecast.xml
    networks:
      - default

  proxy:
    image: "nginx"
    container_name: proxy
    restart: always
    ports:
      - "$NGINX_PORT:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default

networks:
  default:
    name: monkeyradio_diffusion_network
