services:
  diffusion_api:
    build:
      context: ./monkey_diffusion_api
      dockerfile: docker/Dockerfile
    container_name: diffusion_api
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./shared:/shared
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.diffusion_api.rule=PathPrefix(`/`)"
      - "traefik.http.services.diffusion_api.loadbalancer.server.port=3000"

  cache:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    networks:
      - default
    command: redis-server --loglevel warning

  icecast:
    image: "rolla/icecast-kh"
    container_name: icecast2
    restart: always
    volumes:
      - ./icecast/icecast.xml:/home/icecast/config/icecast.xml
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.icecast.rule=PathPrefix(`/v1/diffusion/ice`)"
      - "traefik.http.routers.icecast.service=icecast"
      - "traefik.http.services.icecast.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.ice-strip.stripprefix.prefixes=/v1/diffusion/ice"
      - "traefik.http.middlewares.ice-addprefix.addprefix.prefix=/stream"
      - "traefik.http.routers.icecast.middlewares=ice-strip,ice-addprefix"

  reverse-proxy:
    image: traefik:v3.6
    ports:
      - "$HTTP_PORT:80"
      - "$HTTPS_PORT:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yaml:/traefik.yaml
    labels:
      - "traefik.enable=false"

networks:
  default:
    name: monkeyradio_diffusion_network
    external: true
