services:
  liquidsoap:
    build:
      context: ./liquidsoap
    container_name: liquidsoap
    restart: always
    volumes:
      - ./liquidsoap/confs:/etc/liquidsoap
      - ./shared:/shared
      - ./liquidsoap/persist_output:/persist_output
    networks:
      - default
    command: "liquidsoap /etc/liquidsoap/basic.liq"

  diffusion_api:
    build:
      context: ./monkey_diffusion_api
      dockerfile: docker/Dockerfile
    container_name: diffusion_api
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./shared:/shared
    networks:
      - default

  icecast:
    image: "pltnk/icecast2"
    container_name: icecast2
    restart: always
    volumes:
      - ./icecast/icecast.xml:/etc/icecast2/icecast.xml
    networks:
      - default

  proxy:
    image: "nginx"
    container_name: proxy
    restart: always
    ports:
      - "$NGINX_PORT:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default

networks:
  default:
