services:
  liquidsoap:
    image: "savonet/liquidsoap:v2.2.5"
    container_name: liquidsoap
    restart: always
    volumes:
      - ./liquidsoap/confs:/etc/liquidsoap
      - ./shared/stream_output:/output
      - ./liquidsoap/persist_output:/persist_output
    ports:
      - "$LIQUIDSOAP_PORT:8000"
    command: "liquidsoap /etc/liquidsoap/basic.liq"

  diffusion_api:
    build:
      context: ./monkey_diffusion_api
      dockerfile: docker/Dockerfile
    container_name: diffusion_api
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./shared:/shared
    ports:
      - "$DIFFUSION_API_PORT:3000"

  icecast:
    image: "pltnk/icecast2"
    container_name: icecast2
    restart: always
    ports:
      - $ICECAST_PORT:8000
    volumes:
      - ./icecast/icecast.xml:/etc/icecast2/icecast.xml
