export const SECONDS_IN_MILLISECOND = 1000;
export const MINUTES_IN_MILLISECOND = 60 * SECONDS_IN_MILLISECOND;
export const HOURS_IN_MILLISECOND = 60 * MINUTES_IN_MILLISECOND;
export const DAYS_IN_MILLISECOND = 24 * HOURS_IN_MILLISECOND;
export const WEEKS_IN_MILLISECOND = 7 * DAYS_IN_MILLISECOND;
export const MONTHS_IN_MILLISECOND = 30 * DAYS_IN_MILLISECOND;
export const YEARS_IN_MILLISECOND = 365 * DAYS_IN_MILLISECOND;

