server {
    gzip on;
    gzip_types *;
    gzip_min_length 1024;
    gzip_disable "MSIE [1-6]\.";
    listen 80;
    location /v1/diffusion/ice/ {
        proxy_pass http://icecast:8000/stream/;
    }
    location / {
        proxy_pass http://diffusion_api:3000/;
    }
}
